### PR TITLE
First draft of outline for Skill Graph service

### PR DESCRIPTION
**Pull request by tannerwelsh**
My initial thoughts about what a network of skills/abilities/understandings could look like and how it could serve as the ground upon which we build learning experiences, curriculum, projects, etc.

Still haven't figured out how the linking of a skill to outside resources (a challenge, for example, or a task) should work. Maybe we'd link to skills with a `?ref=` URL parameter so that the skills could record and track the places from which they are referenced and provide a way to visualize/access those references.

For example, if one of our skills is "Relational Database Design [Beginner]", with a url like `https://skills.learnersguild.org/relational-db-design/beginner` then we could create a unique link to reference it from the task "Make a schema to match the data model in the Cookies and Ovens OO project". The Skill Graph would track all these inbound links and associate them with their respective skills/abilities/understandings.

This is one part of a resolution to #14.

### CODE REVIEW

**Comment by tannerwelsh** [comment]
@jeffreywescott & @shereefb any thoughts / suggestions? Does this overlap with anything you've already been thinking of?

**Comment by shereefb** [comment]
I love the use cases you presented, the make a compelling case for some kind of skill graph. I would also add the use case of advanced learners identifying and choosing to explore a new set of skills, but somehow leaving a trail for others to follow and build on.

I think the concept of a "map" is more powerful and apt than a "graph". I also like the word competency more than skill. So "competency map", "mastery map" something like that. 

I'm a little weary that the implementation  you propose is too complex. 

For example, a more simple matrix might be enough:
http://sijinjoseph.com/programmer-competency-matrix/

And here's someone self-assessing themselves on it and modifying it
http://www.sicpers.info/2012/04/on-my-newer-competence/
http://www.sicpers.info/2013/04/rebooting-the-programmer-competency-matrix/

I can imagine this map also being extended to non-tech curriculum topics. 

Dimensions like: emotional, social, feedback....etc. with different levels of mastery for each.

**Comment by shereefb** [comment]
Some interesting discussions here:
https://news.ycombinator.com/item?id=9341146
https://news.ycombinator.com/item?id=4626695

Pretty negative comments in general. Might be saying more about the content of the matrix not the framework of a matrix.

**Comment by tannerwelsh** [comment]
I think the matrix and its critique is a useful place to start / inspiration to use.

And I have some reasons for wanting a graph over a matrix structure which I think validate the complexity involved. Implementation could also be aided by using a graph db like Neo4j.

One major problem with a matrix is that if we want to represent a competency as a prerequisite to more than one other competency, that information has to be duplicated.

For example, say we had the following ability in the graph:

> **Plan for the unexpected**: consider consequences of a program receiving "correct" input, "incorrect" input, and "unexpected" or "irregular" input.

This ability can and should be linked as a "prerequisite" to the following abilities:

> **Follow happy/sad/bad paths**: write test code that exercises source code in common use cases, extreme use cases, and unexpected but possible use cases.

> **Water-tight tests**: use TDD to build robustly tested and resilient software.

And it could be linked to this ability as a "supplement":

> **Debug your intuition**: identify own assumptions about a program and validate them.

Another use case is when we have an ability which could be reached from more than one approach. For example, the ability

> **Automate your local environment**: write executable scripts for common local tasks and include them in your $PATH.

could have many parallel requirements, only one of which would need to be satisfied in order to "unlock" the above ability: i.e. scripting in bash, scripting in Ruby, scripting in Python, scripting with Node.js...

My point being: without a graph structure, these relationships have to be bent to fit into a 2-dimensional matrix, which I feel obscures the true nature of learning and hides the interconnectedness of knowledge and abilities.

**Comment by jeffreywescott** [comment]
@shereefb: can you elaborate on what you mean by a map, and why it's superior to a graph? From a data structures standpoint, maps are generally represented as graphs. In fact, when something like Google Maps computes a route for you, it's doing a "shortest path" algorithmic computation. What would a map look like? Just in terms of how we represent the data.

Graphs are awesome at:
  - path computation
  - expressing dependencies

This, to me, seems an ideal data structure ... much better than at least one other attempt I've seen (which was a tree instead of a graph).

Nerd-alert: [graphs can be represented in a matrix](https://en.wikipedia.org/wiki/Adjacency_matrix).

**Comment by tannerwelsh** [comment]
Adjacency matrices! Whoa. Big nerd high five. :raised_hands:

**Comment by shereefb** [comment]
We’re talking about two different things. 
I’m fine with whatever data structure we end up using.

—

Schedule time with me: http://pick.co/shereef

“Washing one's hands of the conflict between the powerful and the powerless means to side with the powerful, not to be neutral.” - Paulo Freire

“When they tell you to grow up, they mean stop growing.” ~ Tom Robbins

On November 18, 2015 at 2:54:09 PM, Jeffrey Wescott (notifications@github.com) wrote:

@shereefb: can you elaborate on what you mean by a map, and why it's superior to a graph? From a data structures standpoint, maps are generally represented as graphs. In fact, when something like Google Maps computes a route for you, it's doing a "shortest path" algorithmic computation. What would a map look like? Just in terms of how we represent the data.

Graphs are awesome at:

path computation
expressing dependencies
This, to me, seems an ideal data structure ... much better than at least one other attempt I've seen (which was a tree instead of a graph).

Nerd-alert: graphs can be represented in a matrix.

**Comment by jeffreywescott** [comment]
@shereefb cool, thanks.

Still, I'm curious what we might be missing when you talk about a _map_. I understand what you meant by a matrix (since you provided examples), but am wondering if you had something else in mind when you mentioned a "map".

**Comment by tannerwelsh** [comment]
@jeffreywescott I think I can answer your question with [this design proposal](https://app.asana.com/0/65008939926511/67729677531327) and [writeup on a branch of the OS](https://github.com/LearnersGuild/learning-os-blueprint/tree/tw/skills-map/skills-map)

**Comment by jeffreywescott** [comment]
Sweet! Thanks, @tannerwelsh

**Pull request merged**
